
const DATA=JSON.parse(document.getElementById('review-data').textContent);
const labels={schemaVersion:'Версия листа',status:'Статус',approval:'Приёмка',approvalStatus:'Приёмка',role:'Роль',name:'Название',proposedName:'Предложенное название',currentFacts:'Сейчас в коде',proposedBaseline:'Начальные настройки для теста',phaseContract:'Фазы действия',movementContract:'Движение',cancelContract:'Отмена',productionNeeds:'Что изготовить',talents:'Таланты',current:'Сейчас',proposed:'Предложение',currentDescription:'Сейчас',currentEffect:'Сейчас',proposedEffect:'Предложение',effect:'Поведение',numbers:'Числа',interactions:'Сочетания',visualRequirement:'Отображение',vfx:'VFX',animation:'Анимация',animations:'Анимации',sound:'Звук',audio:'Звук',changeStatus:'Изменение',rationale:'Зачем',reason:'Зачем',notes:'Примечания',stableId:'Стабильный ключ',stableKey:'Стабильный ключ',id:'Ключ',key:'Ключ',definitionId:'Идентификатор способности',poolIndex:'Индекс пула',lineIndex:'Линия талантов',proposedId:'Предложенный ключ',talentIndex:'Индекс таланта',damage:'Урон',cooldownTicks:'Перезарядка, тики',lavidiumCost:'Цена, лавидий',windupTicks:'Подготовка, тики',recoveryTicks:'Восстановление, тики',radius:'Радиус',range:'Дальность',durationTicks:'Длительность, тики',approved:'Утверждено',proposed_pending_owner:'Предложение, ждёт решения',pending_owner:'Ждёт решения',existing_unapproved:'Есть в коде, не принято',retained:'Сохранение',reworked:'Переработка',new:'Новый',unchanged:'Без изменения',clarified:'Уточнение',approved_contract:'Утверждённое правило',globalContracts:'Общие правила',basicCombo:'Обычная серия',sources:'Источники',checks:'Проверки',results:'Результаты',warnings:'Ограничения',summary:'Кратко',proposedChanges:'Предлагаемые изменения'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
Object.assign(labels,{damageAt34:'Урон при базовой силе 34',arcDegrees:'Угол сектора, °',basicFireBonusPercent:'Огненная добавка к сабле, %',bladeRadiusM:'Радиус клинка, м',blastRadiusM:'Радиус взрыва, м',channelDrainPerSecond:'Расход удержания, лавидий/с',channelMaxTicks:'Максимум удержания',channelPulseTicks:'Период оборотов',contactTick:'Момент контакта',contactTicks:'Моменты контакта',contactWindowTicks:'Окно попадания',continueWindowTicks:'Окно продолжения',cost:'Цена, лавидий',cycleTicks:'Цикл',damagePerHopAt34:'Урон перехода при базовой силе 34',damageStagesAt34:'Урон трёх этапов при базовой силе 34',distanceM:'Дистанция, м',endTick:'Конец действия',explosionAt34:'Урон взрыва при базовой силе 34',finalStunTicks:'Оглушение финала',hopRangeM:'Дальность перехода, м',hopTicks:'Время перехода',hops:'Количество переходов',launchTick:'Выпуск',lengthM:'Длина, м',maxPools:'Максимум огненных областей',maxTravelTicks:'Максимум полёта',minTravelTicks:'Минимум полёта',poolDiameterM:'Диаметр огненной области, м',poolDurationTicks:'Время огненной области',poolPeriodTicks:'Период урона огня',poolPulseAt34:'Урон импульса огня при базовой силе 34',projectileSpeedMps:'Скорость снаряда, м/с',radiusM:'Радиус, м',randomEvasionPercent:'Случайное уклонение, %',rangeM:'Дальность, м',releaseTick:'Выпуск',retreatM:'Отход, м',stunTicks:'Оглушение',throwRangeM:'Дальность броска, м',travelSpeedMps:'Скорость перемещения, м/с',travelTicks:'Время перемещения',widthM:'Ширина, м',approvalNote:'Что требует решения',approved:'Утверждённая основа',proposedDetails:'Дополнения к обсуждению',rule:'Правило',details:'Подробности',why:'Зачем',model:'Модель',alternativeIfOwnerKeepsFourth:'Альтернатива: сохранить четвёртый удар',proposal:'Предложение',proposal_except_explicit_approved_decisions:'Предложение, кроме отдельно утверждённых правил',approved_behavior_with_proposed_details:'Основа утверждена; детали предложены',approved_behavior_with_proposed_production:'Поведение утверждено; отображение предстоит изготовить',retain:'Сохранить',approved_rework:'Утверждённая правка',optional_rework_requires_owner_choice:'Два варианта к выбору',rebalance:'Изменить числа',clarify:'Уточнить правило',clarify_combo:'Уточнить сочетания',clarify_geometry:'Уточнить область',geometry_fix:'Исправить область',new:'Новый талант'});
Object.assign(labels,{channelPaymentContract:'Оплата удержания',finalContactContract:'Выбор финального удара',controlAcceptanceCases:'Проверки оглушения',acceptanceCases:'Проверочные сценарии',sharedGroundDotContract:'Общие правила наземного огня'});
const title=k=>labels[k]||k.replace(/([a-z])([A-Z])/g,'$1 $2');
function val(x){if(x===null||x===undefined)return '—';if(typeof x==='boolean')return x?'Да':'Нет';if(Array.isArray(x))return '<ul>'+x.map(a=>'<li>'+val(a)+'</li>').join('')+'</ul>';if(typeof x==='object')return fields(x);return esc(labels[x]||x).replace(/\n/g,'<br>')}
function fieldValue(k,v){if(/Ticks?$/.test(k)&&typeof v==='number')return `${esc(v)} тиков · ${Number((v/30).toFixed(3)).toLocaleString('ru')} с`;return val(v)}
function fields(o,skip=[]){return '<dl class="fields">'+Object.entries(o||{}).filter(([k])=>!skip.includes(k)).map(([k,v])=>'<div><dt>'+esc(title(k))+'</dt><dd>'+fieldValue(k,v)+'</dd></div>').join('')+'</dl>'}
function card(name,content,cls=''){return `<div class="card ${cls}"><h3>${esc(name)}</h3>${content}</div>`}
let selected=0;
const skills=DATA.design.skills||[];
function skillName(s){return s.name||s.displayName||s.title||s.proposedName||s.key||'Способность'}
function selectSkill(i){selected=i;let s=skills[i];if(!s)return;document.querySelectorAll('[data-skill]').forEach(b=>b.setAttribute('aria-selected',Number(b.dataset.skill)===i));let top=`<div class="eyebrow">${i+1} / ${skills.length} · ${s.talents?.length||0} талантов</div><h2>${esc(skillName(s))}</h2><p>${esc(s.role||'')}</p>`;let baseline='<div class="two">'+card('Сейчас в коде',val(s.currentFacts||s.current||{}),'current')+card('Предлагаемый вариант',val(s.proposedBaseline||s.proposed||{}),'proposed')+'</div>';let details=fields(s,['name','displayName','title','role','talents','currentFacts','current','proposedBaseline','proposed','poolIndex','id','approval','sources']);let talents=(s.talents||[]).map((t,n)=>`<details class="talent"><summary><span class="talent-num">${n+1}.</span>${esc(t.proposedName||t.name||t.title||t.stableId||'Талант')} <small>${esc(labels[t.changeStatus]||'Предлагаемая правка')}</small></summary><div class="detail-body">${fields(t,['proposedName','name','title','id','idStatus','index','approval','changeStatus','numbers'])}</div></details>`).join('');document.getElementById('skillDetail').innerHTML=top+'<p class="muted">Предлагаемые числа — исходные настройки для игрового теста. 30 тиков = 1 секунда.</p>'+baseline+`<details class="talent"><summary>Фазы, движение, отмены и производство</summary><div class="detail-body">${details}</div></details><h3>Восемь совместимых талантов</h3>`+talents+`<div class="actions"><button id="expandTalents">Развернуть все пункты</button><button id="collapseTalents">Свернуть</button></div>`;document.getElementById('expandTalents').onclick=()=>document.querySelectorAll('#skillDetail details').forEach(d=>d.open=true);document.getElementById('collapseTalents').onclick=()=>document.querySelectorAll('#skillDetail details').forEach(d=>d.open=false)}
function nav(filter=''){let q=filter.toLocaleLowerCase('ru');let match=skills.map((s,i)=>({s,i})).filter(({s})=>JSON.stringify(s).toLocaleLowerCase('ru').includes(q));document.getElementById('skillNav').innerHTML=`<input id="search" placeholder="Поиск навыка или таланта" aria-label="Поиск" value="${esc(filter)}"><div class="skill-count">${skills.length} навыков · ${skills.reduce((n,s)=>n+(s.talents||[]).length,0)} талантов</div>`+match.map(({s,i})=>`<button data-skill="${i}" aria-selected="${selected===i}">${esc(skillName(s))}</button>`).join('');document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>selectSkill(Number(b.dataset.skill)));let input=document.getElementById('search');input.oninput=()=>{let p=input.selectionStart;nav(input.value);let n=document.getElementById('search');n.focus();n.setSelectionRange(p,p)}}
function model(){const m=DATA.model;let out='<div class="notice">'+esc(m.reviewNotice||'Прежняя посадка оружия отклонена: исправляем хват сабли и расстояние якоря до спины. Эти изображения пока сохранены как разбор ошибок.')+'</div>';out+=`<h2>${esc(m.title||'Нынешний Пелаг · оптимизация и якорь за спиной')}</h2><p>${esc(m.summary||'Материалы первого этапа готовятся.')}</p>`;if(m.stats)out+='<div class="stats">'+m.stats.map(s=>`<div class="stat"><b>${esc(s.value)}</b><span>${esc(s.label)}</span></div>`).join('')+'</div>';if(m.notes)out+=card('Что проверено',val(m.notes));if(m.images?.length)out+='<div class="grid gallery">'+m.images.map(i=>`<figure class="${i.wide?'wide':''}"><a href="${esc(i.path)}" target="_blank"><img class="photo" src="${esc(i.path)}" alt="${esc(i.title)}" loading="lazy"></a><figcaption><strong>${esc(i.title)}</strong>${i.caption?'<p>'+esc(i.caption)+'</p>':''}</figcaption></figure>`).join('')+'</div>';if(m.videos?.length)out+='<div class="grid gallery">'+m.videos.map(v=>`<figure><video controls loop muted playsinline preload="metadata" src="${esc(v.path)}"></video><figcaption>${esc(v.title)}</figcaption></figure>`).join('')+'</div>';if(m.posePreflight){const p=m.posePreflight;out+='<details class="talent"><summary>Посадка оружия в крайних позах</summary><div class="detail-body"><p>'+esc(p.summary)+'</p><div class="grid gallery">'+p.images.map(i=>'<figure><a href="'+esc(i.path)+'" target="_blank"><img class="photo" src="'+esc(i.path)+'" alt="'+esc(i.title)+'" loading="lazy"></a><figcaption>'+esc(i.title)+'</figcaption></figure>').join('')+'</div><p class="muted">'+esc(p.limitation)+'</p></div></details>';}if(m.downloads?.length)out+='<div class="actions">'+m.downloads.map(d=>`<a href="${esc(d.path)}">${esc(d.title)}</a>`).join(' · ')+'</div>';if(m.limitations)out+=card('Что ещё проверяем до установки',val(m.limitations));document.getElementById('model').innerHTML=out}
const phases=['Модель и оружие: сравнение и приёмка','Базовые движения и трёхударная серия в игре','Вихрь: принятый базовый VFX и все восемь талантов','Остальные навыки: Рассекающий → масло → На вылет → Отбой → Шквал → Удар якорем → Крушение → Абордаж → Смесь','Общий забег, баланс трёх сборок, звук и производительность'];
const brief=DATA.brief||{};
const shortText=v=>typeof v==='string'?v:(v.text||v.description||v.proposal||v.title||'');
const basics=(brief.battleBasics||[]).map(b=>'<li>'+esc(shortText(b))+'</li>').join('');
const choices=(brief.majorChoices||[]).map(c=>'<li><strong>'+esc(c.title)+'</strong> — '+esc(c.proposal)+'</li>').join('');
const shortSkills=(brief.skills||[]).map(s=>'<details class="talent"><summary>'+esc(s.name)+'<br><small>'+esc(s.changeSummary||s.role)+'</small></summary><div class="detail-body"><ol>'+s.talents.map(t=>'<li><strong>'+esc(t.name)+'</strong> — '+esc(t.effect)+'</li>').join('')+'</ol><p class="muted">Предложения, а не уже установленные изменения.</p></div></details>').join('');
document.getElementById('briefReview').innerHTML=card('Основа боя — в шести пунктах','<ul>'+basics+'</ul>')+'<h2>Что предлагаю по навыкам</h2><p class="muted">Нажми на навык: внутри восемь талантов, каждый одной строкой.</p>'+shortSkills+'<details class="talent"><summary>Основные решения, которые ещё нужно выбрать</summary><div class="detail-body"><ul>'+choices+'</ul></div></details>';
document.getElementById('rules').innerHTML='<h2>Основа боя</h2>'+card('Коротко','<ul>'+basics+'</ul>')+'<h2>Порядок работы</h2>'+phases.map((p,i)=>`<div class="card phase"><b>${i+1}</b><div>${esc(p)}</div></div>`).join('')+'<details class="talent"><summary>Подробные правила расчёта</summary><div class="detail-body">'+card('Обычная серия',val(DATA.design.basicCombo||{}))+card('Общие правила',val(DATA.design.globalContracts||{}))+card('Наземный огонь: предложение',val(DATA.design.sharedGroundDotContract||{}))+'</div></details><div class="notice">Один клип за раз: конкретный референс Higgsfield с нашим героем → Blender → проверка в игре. Только базовый VFX Вихря уже принят.</div>';
document.getElementById('audit').innerHTML='<h2>Техническая основа и ограничения</h2><p>Здесь результаты чтения проекта и исходная точка. Это не отчёт о завершении всего прохода Пелага.</p>'+card('Что установлено','<ul><li>Хранение выбранных талантов уже рассчитано на десять навыков. Каталог сейчас содержит 64 таланта; новые шестнадцать ещё не реализованы.</li><li>Уровень, деньги и зелья сохраняются отдельно от талантов забега. Само расширение каталога до 80 не требует новой версии лагерного сохранения.</li><li>Исходники и зависимости принятого Вихря зафиксированы контрольными суммами.</li><li>Внешняя волна Вихря имеет урон, но не имеет собственного отображения. Геометрия комбинации веера и дальней волны Рассекающего также требует исправления.</li><li>Перед изменениями Пелага прошли 541 тест симуляции и 32 теста представления. Новые механики ими пока не проверялись.</li></ul>')+`<details class="talent"><summary>Подробный технический аудит и источники</summary><div class="detail-body">${fields(DATA.audit)}</div></details><div class="actions"><a href="../design/ability-passports.json">Полный лист JSON</a><a href="../design/production-audit.json">Аудит JSON</a><a href="../validation/sim-baseline.trx">Исходные тесты симуляции</a><a href="../validation/presentation-baseline.trx">Исходные тесты представления</a></div>`;
const concepts=DATA.concepts||{};
document.getElementById('concepts').innerHTML='<h2>'+esc(concepts.title||'Визуальные предложения')+'</h2><p>'+esc(concepts.summary||'')+'</p><div class="grid gallery">'+(concepts.images||[]).map(c=>'<figure class="wide"><a href="'+esc(c.path)+'" target="_blank"><img class="photo" src="'+esc(c.path)+'" alt="'+esc(c.title)+'" loading="lazy"></a><figcaption><strong>'+esc(c.title)+'</strong><p>'+esc(c.caption)+'</p></figcaption></figure>').join('')+'</div><p class="muted">'+esc(concepts.cost||'')+'</p>';
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('main>section').forEach(s=>s.hidden=s.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(t=>t.setAttribute('aria-selected',t===b));history.replaceState(null,'','#'+b.dataset.tab)});
model();nav();selectSkill(0);let tab=location.hash.slice(1);document.querySelector(`[data-tab="${CSS.escape(tab)}"]`)?.click();
