import json

d = json.load(open("prompts.json"))

MEDIA = {
    "r1_scene.jpg": "523b4e73-2361-4124-a34c-70183e4efd33",
    "r2_model.jpg": "91cbe17d-d6be-4247-a02e-22572b2efb5a",
    "r3_anchor.jpg": "63c0a31a-3023-47aa-b8a5-3331e12aa5b8",
    "r4_quake.jpg": "3f38dfae-ff80-46fc-a646-3f6cfd3b72ad",
    "icon_Whirlwind.jpg": "ce803e36-43af-4a30-88e5-6f964527d442",
    "icon_Squall.jpg": "f3eab272-e266-4882-be87-1bfbf6797f9a",
    "icon_AnchorLeap_Geyser.jpg": "b3c71385-a256-4739-bc36-2688237b273d",
}
FR = ["r1_scene.jpg", "r2_model.jpg", "r3_anchor.jpg", "r4_quake.jpg"]
IC = ["icon_Whirlwind.jpg", "icon_Squall.jpg", "icon_AnchorLeap_Geyser.jpg", "r3_anchor.jpg"]
JOBS = {
    "A-earth-v1": "640321e5-19d4-40bd-8717-2cd122cd7ca6",
    "A-earth-v2": "5a2460a2-9b3e-4f66-bca2-20070257a176",
    "B-deep-v1": "40da0344-5964-4e31-a961-3e3175949dbc",
    "B-deep-v2": "3f3c98e4-86c1-46af-8c52-fca6f8a4bede",
    "C-iron-v1": "e9b422be-2591-41ee-9522-a634ed0c0f9b",
    "C-iron-v2": "0359844d-552d-4f34-87a9-763a2b5ffbc4",
    "silhouettes-v1": "3d1eb913-6bd3-4b4f-aa57-0be23d4b1bf8",
    "silhouettes-v2": "8a1afa3f-02e3-44e8-8441-ba8906c1af9a",
}

man = {
    "date": "2026-10-06",
    "model": "gpt_image_2_5",
    "credits": {"before": 50.3, "after": 45.3, "spent": 5.0, "budget": 15},
    "uploaded_refs": {k: {"media_id": v, "local": "refs/" + k} for k, v in MEDIA.items()},
    "jobs": [],
    "notes": "C-iron-v1 and B-deep-v2 were first rejected at submission with 429 rate_limit_reached (no job, no charge) and resubmitted with the same params.",
}
for k, p in d["frames"].items():
    man["jobs"].append({"name": k, "job_id": JOBS[k], "file": "frames/%s.png" % k, "quality": "medium",
                        "resolution": "1k", "aspect_ratio": "16:9", "refs": FR, "status": "completed"})
for k, p in d["icons"].items():
    man["jobs"].append({"name": k, "job_id": JOBS[k], "file": "icons/%s.png" % k, "quality": "medium",
                        "resolution": "2k", "aspect_ratio": "21:9", "refs": IC, "status": "completed"})
man["derived"] = ["icons-current-sheet.jpg", "icons/compare-v1.jpg", "icons/compare-v2.jpg",
                  "icons/v1-Wreck-512.png", "icons/v1-AnchorThrow-512.png", "icons/v1-Abordage-512.png",
                  "icons/v2-Wreck-512.png", "icons/v2-AnchorThrow-512.png", "icons/v2-Abordage-512.png"]
json.dump(man, open("manifest.json", "w"), indent=1)

L = []
L.append("# Wreck look 2026-10-06: exact prompts")
L.append("")
L.append("Model gpt_image_2_5, role image_references. Every prompt was sent as ONE line, ASCII only (see higgsfield-prompt-gotchas).")
L.append("Frames: medium, 1k, 16:9, refs r1_scene, r2_model, r3_anchor, r4_quake (in that order).")
L.append("Icon sheets: medium, 2k, 21:9, refs icon_Whirlwind, icon_Squall, icon_AnchorLeap_Geyser, r3_anchor.")
L.append("Each prompt = shared base + direction text + composition line; generated by build_prompts.py, source of truth prompts.json.")
L.append("")
for k, p in d["frames"].items():
    L.append("## frames/%s.png  (job %s)" % (k, JOBS[k]))
    L.append("")
    L.append("```")
    L.append(p)
    L.append("```")
    L.append("")
for k, p in d["icons"].items():
    L.append("## icons/%s.png  (job %s)" % (k, JOBS[k]))
    L.append("")
    L.append("```")
    L.append(p)
    L.append("```")
    L.append("")
open("prompts.md", "w", encoding="utf-8").write("\n".join(L))
print("ok", len(L))
