
const $=id=>document.getElementById(id),cache=[];let frame=0,view='side',comparison='old',running=false,started=0,first=0,rate=1,lastKey='';
const filename=f=>String(f).padStart(4,'0');
function draw(){const key=`${frame}/${view}/${comparison}`;if(key!==lastKey){$('animation').src=`${view}_frames/${filename(frame)}.png`;$('reference').src=comparison==='old'?`../animation_death/${view}_frames/${filename(frame)}.png`:`reference_frames/${filename(frame)}.jpg`;lastKey=key;}$('seek').value=frame;$('counter').value=`Кадр ${frame} / 60 · ${(frame/30).toFixed(2).replace('.',',')} с`;$('phase').textContent=frame<8?'Потеря опоры':frame<20?'Подгибаются передние ноги':frame<32?'Оседает корпус':frame<44?'Таз и голова опускаются':frame<48?'Затухание':'Неподвижное тело';$('viewLabel').textContent=`${view==='side'?'Сбоку':'С игровой камеры'} · 2 секунды`;if(!$('play').disabled)$('play').textContent=running?'Пауза':frame===60?'Ещё раз':'Смотреть';}
function seek(f){running=false;frame=Math.max(0,Math.min(60,f));draw();}
function toggle(){if($('play').disabled)return;if(!running&&frame===60)frame=0;running=!running;first=frame;started=performance.now();draw();}
for(const [id,value] of [['oldVersion','old'],['videoReference','reference']])$(id).onclick=()=>{comparison=value;$('comparisonTitle').textContent=value==='old'?'Предыдущая версия':'Принятый видеореференс';$('comparisonNote').textContent=value==='old'?'Отклонена: туловище сминается при падении.':'Higgsfield · кадры сопоставлены по фазам падения.';$('oldVersion').setAttribute('aria-pressed',String(value==='old'));$('videoReference').setAttribute('aria-pressed',String(value==='reference'));draw();};
$('play').onclick=toggle;$('reset').onclick=()=>seek(0);$('prev').onclick=()=>seek(frame-1);$('next').onclick=()=>seek(frame+1);$('seek').oninput=()=>seek(Number($('seek').value));$('speed').onchange=()=>{rate=Number($('speed').value);first=frame;started=performance.now();};
for(const name of ['side','game'])$(name).onclick=()=>{view=name;for(const other of ['side','game'])$(other).setAttribute('aria-pressed',String(name===other));draw();};
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();toggle();}if(e.code==='ArrowRight'){e.preventDefault();seek(frame+1);}if(e.code==='ArrowLeft'){e.preventDefault();seek(frame-1);}});
function tick(now){if(running){const elapsed=first+Math.floor((now-started)*30*rate/1000);if(elapsed>60){if($('repeat').checked){frame=elapsed%61;first=frame;started=now;}else{frame=60;running=false;}}else frame=elapsed;draw();}requestAnimationFrame(tick);}requestAnimationFrame(tick);draw();
const assets=[];for(let f=0;f<=60;f++){assets.push(`reference_frames/${filename(f)}.jpg`);for(const v of ['side','game']){assets.push(`${v}_frames/${filename(f)}.png`);assets.push(`../animation_death/${v}_frames/${filename(f)}.png`);}}let loaded=0,failed=0;
function done(error){loaded++;if(error)failed++;$('loading').textContent=`Загружено ${loaded} из ${assets.length}`;if(loaded===assets.length){$('play').disabled=failed>0;$('loading').textContent=failed?'Часть кадров недоступна. Ниже есть обычные видеозаписи.':'Готово · можно смотреть и переключать камеры';draw();}}
for(const path of assets){const im=new Image();cache.push(im);im.onload=()=>done(false);im.onerror=()=>done(true);im.src=path;}
